# accessdb
# Autogenerated from man page /nix/store/jm090ms8ngq3c5g9v5jd0djplphnc8dr-man-db-2.9.4/share/man/man8/accessdb.8.gz
complete -c accessdb -s d -l debug -d 'Print debugging information'
complete -c accessdb -s '?' -l help -d 'Print a help message and exit'
complete -c accessdb -l usage -d 'Print a short usage message and exit'
complete -c accessdb -s V -l version -d 'Display version information.  AUTHOR'

