# cmp
# Autogenerated from man page /nix/store/kjx1mv85c5cgsrr4bwar22j7hbwj834m-diffutils-3.7/share/man/man1/cmp.1.gz
complete -c cmp -s b -l print-bytes -d 'print differing bytes'
complete -c cmp -s i -l ignore-initial -d 'skip first SKIP bytes of both inputs'
complete -c cmp -s l -l verbose -d 'output byte numbers and differing byte values'
complete -c cmp -s n -l bytes -d 'compare at most LIMIT bytes'
complete -c cmp -s s -l quiet -l silent -d 'suppress all normal output'
complete -c cmp -l help -d 'display this help and exit'
complete -c cmp -s v -l version -d 'output version information and exit'

