# esdcompat
# Autogenerated from man page /nix/store/mav4251if1ahjq5vkpwycyyvnmy459c4-pulseaudio-14.2/share/man/man1/esdcompat.1.gz
complete -c esdcompat -s h -l help -d 'Show help'
complete -c esdcompat -l version -d 'Show version information'
complete -c esdcompat -o tcp -o promiscuous -s d -s b -s r -o as -o unix -o public -o terminate -o nobeeps -o trust -o port -o bind -d 'These options understood by the original esd are ignored by esdcompat'
complete -c esdcompat -o spawnpid -o spawnfd -d 'These internally used options understood by the original esd are properly han…'

