# evcd2vcd
# Autogenerated from man page /nix/store/glh1jj2vy9h9h7nis6hf3lmrdknlyyl8-gtkwave-3.3.110/share/man/man1/evcd2vcd.1.gz
complete -c evcd2vcd -s f -l filename -d 'Specify EVCD input filename'
complete -c evcd2vcd -s h -l help -d 'Show help screen'

