# fish_key_reader
# Autogenerated from man page /nix/store/rr5zi9bqfzbb5f42bqi69ca1lhiqd2vd-fish-3.3.1/share/man/man1/fish_key_reader.1.gz
complete -c fish_key_reader -s c -l continuous -d 'o 2'
complete -c fish_key_reader -s h -l help -d 'o 2'
complete -c fish_key_reader -s v -l version

