# fish_indent
# Autogenerated from man page /nix/store/rr5zi9bqfzbb5f42bqi69ca1lhiqd2vd-fish-3.3.1/share/man/man1/fish_indent.1.gz
complete -c fish_indent -s w -l write -d 'o 2'
complete -c fish_indent -s i -l no-indent -d 'o 2'
complete -c fish_indent -s c -l check -d 'o 2'
complete -c fish_indent -s v -l version -d 'o 2'
complete -c fish_indent -l ansi -d 'o 2'
complete -c fish_indent -l html -d 'o 2'
complete -c fish_indent -s d -l debug -d 'o 2'
complete -c fish_indent -s o -l debug-output -d 'o 2'
complete -c fish_indent -l dump-parse-tree

