# fst2vcd
# Autogenerated from man page /nix/store/glh1jj2vy9h9h7nis6hf3lmrdknlyyl8-gtkwave-3.3.110/share/man/man1/fst2vcd.1.gz
complete -c fst2vcd -s f -l fstname -d 'Specify FST input filename'
complete -c fst2vcd -s o -l output -d 'Specify optional VCD output filename'
complete -c fst2vcd -s e -l 'extensions\\Fr' -d 'Emit FST extensions to VCD'

