# git-write-tree
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-write-tree.1.gz
complete -c git-write-tree -l missing-ok -d 'Normally git write-tree ensures that the objects referenced by the directory …'
complete -c git-write-tree -l prefix -d 'Writes a tree object that represents a subdirectory <prefix>'

