# git-credential-cache
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-credential-cache.1.gz
complete -c git-credential-cache -l timeout -d 'Number of seconds to cache credentials (default: 900)'
complete -c git-credential-cache -l socket -d 'Use <path> to contact a running cache daemon (or start a new cache daemon if …'

