# git-for-each-repo
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-for-each-repo.1.gz
complete -c git-for-each-repo -l config -d 'Use the given config variable as a multi-valued list storing absolute path na…'

