# git-web--browse
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-web--browse.1.gz
complete -c git-web--browse -s b -l browser -d 'Use the specified browser.  It must be in the list of supported browsers'
complete -c git-web--browse -s t -l tool -d 'Same as above'
complete -c git-web--browse -s c -l config -d 'CONF. VAR is looked up in the Git config files'

