# git-stripspace
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-stripspace.1.gz
complete -c git-stripspace -s s -l strip-comments -d 'Skip and remove all lines starting with comment character (default #)'
complete -c git-stripspace -s c -l comment-lines -d 'Prepend comment character and blank to each line'

