# git-cherry
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-cherry.1.gz
complete -c git-cherry -s v -d 'Show the commit subjects next to the SHA1s'

