# git-verify-tag
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-verify-tag.1.gz
complete -c git-verify-tag -l raw -d 'Print the raw gpg status output to standard error instead of the normal human…'
complete -c git-verify-tag -s v -l verbose -d 'Print the contents of the tag object before validating it'

