# git-prune-packed
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-prune-packed.1.gz
complete -c git-prune-packed -s n -l dry-run -d 'Don\'t actually remove any objects, only show those that would have been remov…'
complete -c git-prune-packed -s q -l quiet -d 'Squelch the progress indicator'

