# git-pack-refs
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-pack-refs.1.gz
complete -c git-pack-refs -l all -d 'The command by default packs all tags and refs that are already packed, and l…'
complete -c git-pack-refs -l no-prune -d 'The command usually removes loose refs under $GIT_DIR/refs hierarchy after pa…'

