# git-pack-redundant
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-pack-redundant.1.gz
complete -c git-pack-redundant -l all -d 'Processes all packs.  Any filenames on the command line are ignored'
complete -c git-pack-redundant -l alt-odb -d 'Don\'t require objects present in packs from alternate object directories to b…'
complete -c git-pack-redundant -l verbose -d 'Outputs some statistics to stderr.  Has a small performance penalty'

