# git-check-mailmap
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-check-mailmap.1.gz
complete -c git-check-mailmap -l stdin -d 'Read contacts, one per line, from the standard input after exhausting contact…'

