# git-mktree
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-mktree.1.gz
complete -c git-mktree -s z -d 'Read the NUL-terminated ls-tree -z output instead'
complete -c git-mktree -l missing -d 'Allow missing objects'
complete -c git-mktree -l batch -d 'Allow building of more than one tree object before exiting'

