# git-show-index
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-show-index.1.gz
complete -c git-show-index -l object-format -d 'Specify the given object format (hash algorithm) for the index file'

