# git-credential-store
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-credential-store.1.gz
complete -c git-credential-store -l file -d 'Use <path> to lookup and store credentials'

