# git-verify-commit
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-verify-commit.1.gz
complete -c git-verify-commit -l raw -d 'Print the raw gpg status output to standard error instead of the normal human…'
complete -c git-verify-commit -s v -l verbose -d 'Print the contents of the commit object before validating it'

