# git-subtree
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-subtree.1.gz
complete -c git-subtree -l squash -d 'merge <local-commit>'
complete -c git-subtree -l annotate -d 'git merge and friends will work as expected.  pull <repository> <remote-ref>'
complete -c git-subtree -s q -l quiet
complete -c git-subtree -s d -l debug
complete -c git-subtree -s P -l prefix
complete -c git-subtree -s m -l message
complete -c git-subtree -l rejoin
complete -c git-subtree -s b -l branch
complete -c git-subtree -l ignore-joins
complete -c git-subtree -l onto

