# git-count-objects
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-count-objects.1.gz
complete -c git-count-objects -s v -l verbose -d 'Report in more detail: . sp count: the number of loose objects '
complete -c git-count-objects -s H -l human-readable -d 'Print sizes in human readable format'

