# git-sparse-checkout
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-sparse-checkout.1.gz
complete -c git-sparse-checkout -l cone -d 'is provided, the core'
complete -c git-sparse-checkout -l sparse-index -d 'option to toggle the use of the sparse index format'
complete -c git-sparse-checkout -l stdin -d 'option is provided, the patterns are read from standard in as a newline-delim…'

