# git-verify-pack
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-verify-pack.1.gz
complete -c git-verify-pack -s v -l verbose -d 'After verifying the pack, show list of objects contained in the pack and a hi…'
complete -c git-verify-pack -s s -l stat-only -d 'Do not verify the pack contents; only show the histogram of delta chain length'

