# git-mv
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-mv.1.gz
complete -c git-mv -s f -l force -d 'Force renaming or moving of a file even if the target exists'
complete -c git-mv -s k -d 'Skip move or rename actions which would lead to an error condition'
complete -c git-mv -s n -l dry-run -d 'Do nothing; only show what would happen'
complete -c git-mv -s v -l verbose -d 'Report the names of files as they are moved'

