# git-mktag
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-mktag.1.gz
complete -c git-mktag -l strict -d 'By default mktag turns on the equivalent of git-fsck(1) --strict mode'
complete -c git-mktag -l no-strict -d 'to disable it'

