# git-request-pull
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-request-pull.1.gz
complete -c git-request-pull -s p -d 'Include patch text in the output'

