# git-bugreport
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/git-bugreport.1.gz
complete -c git-bugreport -s o -l output-directory -d 'Place the resulting bug report file in <path> instead of the current directory'
complete -c git-bugreport -s s -l suffix -d 'Specify an alternate suffix for the bugreport name, to create a file named gi…'

