# gitweb
# Autogenerated from man page /nix/store/jha53c5kh54c46fgywh37v3m3h4hcl0k-git-2.34.1/share/man/man1/gitweb.1.gz
complete -c gitweb -l export-all -d 'option is used) allows pulling only for those repositories that have git-daem…'

