# iverilog-vpi
# Autogenerated from man page /nix/store/q0rhxcs2hfri6ja2fas671ywiszk20qr-iverilog-11.0/share/man/man1/iverilog-vpi.1.gz
complete -c iverilog-vpi -o llibrary -d 'Include the named library in the link of the VPI module'
complete -c iverilog-vpi -o Ldirectory -d 'Add directory to the list of directories that will be searched for library fi…'
complete -c iverilog-vpi -o Idirectory -d 'Add directory to the list of directories that will be searched for header fil…'
complete -c iverilog-vpi -o Ddefine -d 'Define a macro named define'
complete -c iverilog-vpi -l name -d 'Normally, the output VPI module will be named after the first source file pas…'
complete -c iverilog-vpi -o mingw -d 'Tell the program the root of the MinGW compiler tool suite'
complete -c iverilog-vpi -l install-dir -d 'Print the install directory for VPI modules'
complete -c iverilog-vpi -l cflags -d 'Print the compiler flags (CFLAGS or CXXFLAGS) needed to compile source code d…'
complete -c iverilog-vpi -l ldflags -d 'Print the linker flags (LDFLAGS) needed to link a VPI module'
complete -c iverilog-vpi -l ldlibs -d 'Print the libraries (LDLIBS) needed to link a VPI module'

