# lxt2vcd
# Autogenerated from man page /nix/store/glh1jj2vy9h9h7nis6hf3lmrdknlyyl8-gtkwave-3.3.110/share/man/man1/lxt2vcd.1.gz
complete -c lxt2vcd -s l -l lxtname -d 'Specify LXT2 input filename'
complete -c lxt2vcd -s o -l output -d 'Specify optional VCD output filename'
complete -c lxt2vcd -s f -l flatearth -d 'Emit flattened hierarchies'
complete -c lxt2vcd -s n -l notruncate -d 'Do not shorten bitvectors'
complete -c lxt2vcd -s h -l help -d 'Display help then exit'

