# nix-hash
# Autogenerated from man page /home/runner/.nix-profile/share/man/man1/nix-hash.1.gz
complete -c nix-hash -l flat -d 'Print the cryptographic hash of the contents of each regular file path'
complete -c nix-hash -l base32 -d 'Print the hash in a base-32 representation rather than hexadecimal'
complete -c nix-hash -l truncate -d 'Truncate hashes longer than 160 bits (such as SHA-256) to 160 bits'
complete -c nix-hash -l type -d 'Use the specified cryptographic hash algorithm, which can be one of md5, sha1…'
complete -c nix-hash -l to-base16 -d 'Don\'t hash anything, but convert the base-32 hash representation hash to hexa…'
complete -c nix-hash -l to-base32 -d 'Don\'t hash anything, but convert the hexadecimal hash representation hash to …'

