# nix-env
# Autogenerated from man page /home/runner/.nix-profile/share/man/man1/nix-env.1.gz
complete -c nix-env -l file -s f
complete -c nix-env -l install
complete -c nix-env -l upgrade
complete -c nix-env -l query -l available -d 'operations to obtain derivations.  The default is ~/. nix-defexpr'
complete -c nix-env -l profile -s p
complete -c nix-env -l dry-run
complete -c nix-env -l uninstall
complete -c nix-env -l switch-generation
complete -c nix-env -l delete-generations -d and
complete -c nix-env -l rollback -d 'operations, this flag will cause nix-env to print what would be done if this …'
complete -c nix-env -l system-filter
complete -c nix-env -l help
complete -c nix-env -l version
complete -c nix-env -l verbose -s v
complete -c nix-env -l quiet
complete -c nix-env -l no-build-output -s Q
complete -c nix-env -l max-jobs -s j
complete -c nix-env -l cores
complete -c nix-env -o jN -d 'flag to GNU Make'
complete -c nix-env -l max-silent-time
complete -c nix-env -l timeout
complete -c nix-env -l keep-going -s k
complete -c nix-env -l keep-failed -s K
complete -c nix-env -l fallback
complete -c nix-env -l no-build-hook
complete -c nix-env -l readonly-mode
complete -c nix-env -l arg
complete -c nix-env -l argstr
complete -c nix-env -l attr -s A
complete -c nix-env -l expr -s E
complete -c nix-env -s I
complete -c nix-env -l option
complete -c nix-env -l repair
complete -c nix-env -l preserve-installed -d 'is specified'
complete -c nix-env -l from-profile -d 'path is given, args is a set of names denoting installed store paths in the p…'
complete -c nix-env -l from-expression -d 'is given, args are Nix functions that are called with the active Nix expressi…'
complete -c nix-env -l prebuilt-only -s b
complete -c nix-env -s P
complete -c nix-env -l remove-all -s r
complete -c nix-env -l lt
complete -c nix-env -l leq
complete -c nix-env -l eq
complete -c nix-env -l always
complete -c nix-env -l set -d 'operation modifies the current generation of a profile so that it contains ex…'
complete -c nix-env -l set-flag -d 'operation allows meta attributes of installed packages to be modified'
complete -c nix-env -l installed
complete -c nix-env -s a
complete -c nix-env -l no-name -d 'is specified'
complete -c nix-env -l xml
complete -c nix-env -l json
complete -c nix-env -l status -s s
complete -c nix-env -l attr-path
complete -c nix-env -l compare-versions -s c
complete -c nix-env -l system
complete -c nix-env -l drv-path
complete -c nix-env -l out-path
complete -c nix-env -l description
complete -c nix-env -l meta
complete -c nix-env -o P-
complete -c nix-env -l S
complete -c nix-env -l list-generations -d and

