# nix-copy-closure
# Autogenerated from man page /home/runner/.nix-profile/share/man/man1/nix-copy-closure.1.gz
complete -c nix-copy-closure -l from -d 'paths on a remote machine is copied to the Nix store on the local machine'
complete -c nix-copy-closure -l to
complete -c nix-copy-closure -l gzip
complete -c nix-copy-closure -l include-outputs
complete -c nix-copy-closure -l use-substitutes -s s
complete -c nix-copy-closure -s v

