# nix-channel
# Autogenerated from man page /home/runner/.nix-profile/share/man/man1/nix-channel.1.gz
complete -c nix-channel -l add
complete -c nix-channel -o stable -d or
complete -c nix-channel -o unstable -d removed
complete -c nix-channel -l remove
complete -c nix-channel -l list
complete -c nix-channel -l update
complete -c nix-channel -l rollback

