# nix-prefetch-url
# Autogenerated from man page /home/runner/.nix-profile/share/man/man1/nix-prefetch-url.1.gz
complete -c nix-prefetch-url -l type -d 'Use the specified cryptographic hash algorithm, which can be one of md5, sha1…'
complete -c nix-prefetch-url -l print-path -d 'Print the store path of the downloaded file on standard output'
complete -c nix-prefetch-url -l unpack -d 'Unpack the archive (which must be a tarball or zip file) and add the result t…'
complete -c nix-prefetch-url -l name -d 'Override the name of the file in the Nix store'

