# nix-collect-garbage
# Autogenerated from man page /home/runner/.nix-profile/share/man/man1/nix-collect-garbage.1.gz
complete -c nix-collect-garbage -s d -d '(--delete-old), which deletes all old generations of all profiles in /nix/var…'
complete -c nix-collect-garbage -l delete-older-than -d 'period, where period is a value such as 30d, which deletes all generations ol…'

