# pacmd
# Autogenerated from man page /nix/store/mav4251if1ahjq5vkpwycyyvnmy459c4-pulseaudio-14.2/share/man/man1/pacmd.1.gz
complete -c pacmd -s h -l help -d 'Show help'
complete -c pacmd -l version -d 'Show version information'

