# pactl
# Autogenerated from man page /nix/store/mav4251if1ahjq5vkpwycyyvnmy459c4-pulseaudio-14.2/share/man/man1/pactl.1.gz
complete -c pactl -s h -l help -d 'Show help'
complete -c pactl -l version -d 'Show version information'
complete -c pactl -s s -l server -d 'Choose the server to connect to'
complete -c pactl -s n -l client-name -d 'Specify the client name pactl shall pass to the server when connecting'

