# pasuspender
# Autogenerated from man page /nix/store/mav4251if1ahjq5vkpwycyyvnmy459c4-pulseaudio-14.2/share/man/man1/pasuspender.1.gz
complete -c pasuspender -s h -l help -d 'Show help'
complete -c pasuspender -l version -d 'Show version information'
complete -c pasuspender -s s -l server -d 'Specify the sound server to connect to'

