# updatedb
# Autogenerated from man page /nix/store/ihxk2vlm0vi7c4j3gpm084kbxvz6v585-findutils-4.8.0/share/man/man1/updatedb.1.gz
complete -c updatedb -l findoptions -o 'option2...\'' -d 'Global options to pass on to find'
complete -c updatedb -l localpaths -d 'Non-network directories to put in the database.  Default is /'
complete -c updatedb -l netpaths -d 'Network (NFS, AFS, RFS, etc. ) directories to put in the database'
complete -c updatedb -l prunepaths -d 'Directories to not put in the database, which would otherwise be'
complete -c updatedb -l prunefs -d 'File systems to not put in the database, which would otherwise be'
complete -c updatedb -l output -d 'The database file to build.  Default is system-dependent'
complete -c updatedb -l localuser -d 'The user to search non-network directories as, using su(1)'
complete -c updatedb -l netuser -d 'The user to search network directories as, using su(1).  Default is daemon'
complete -c updatedb -l dbformat -d 'Create the database in format F.   The default format is called LOCATE02'
complete -c updatedb -l version -d 'Print the version number of  updatedb and exit'
complete -c updatedb -l help -d 'Print a summary of the options to updatedb and exit'

