# vcd2lxt2
# Autogenerated from man page /nix/store/glh1jj2vy9h9h7nis6hf3lmrdknlyyl8-gtkwave-3.3.110/share/man/man1/vcd2lxt2.1.gz
complete -c vcd2lxt2 -s v -l vcdname -d 'Specify VCD input filename'
complete -c vcd2lxt2 -s l -l lxtname -d 'Specify LXT2 output filename'
complete -c vcd2lxt2 -s d -l depth -d 'Specify 0. 9 gzip compression depth, default is 4'
complete -c vcd2lxt2 -s m -l maxgranule -d 'Specify number of granules per section, default is 8'
complete -c vcd2lxt2 -s b -l break -d 'Specify break size (default = 0 = off)'
complete -c vcd2lxt2 -s p -l partialmode -d 'Specify partial zip mode 0 = monolithic, 1 = separation'
complete -c vcd2lxt2 -s c -l checkpoint -d 'Specify checkpoint mode.   0 is on which is default, and 1 is off'
complete -c vcd2lxt2 -s h -l help -d 'Show help screen'

