# vcd2vzt
# Autogenerated from man page /nix/store/glh1jj2vy9h9h7nis6hf3lmrdknlyyl8-gtkwave-3.3.110/share/man/man1/vcd2vzt.1.gz
complete -c vcd2vzt -s v -l vcdname -d 'Specify VCD input filename'
complete -c vcd2vzt -s l -l vztname -d 'Specify VZT output filename'
complete -c vcd2vzt -s d -l depth -d 'Specify 0. 9 gzip compression depth, default is 4'
complete -c vcd2vzt -s m -l maxgranule -d 'Specify number of granules per section, default is 8'
complete -c vcd2vzt -s b -l break -d 'Specify break size (default = 0 = off)'
complete -c vcd2vzt -s z -l ziptype -d 'Specify zip type (default = 0 gzip, 1 = bzip2, 2 = lzma)'
complete -c vcd2vzt -s t -l twostate -d 'Forces MVL2 twostate mode (default is MVL4)'
complete -c vcd2vzt -s r -l rle -d 'Uses an bitwise RLE compression on the value table.   Default is off'
complete -c vcd2vzt -s h -l help -d 'Show help screen'

