# vcd2fst
# Autogenerated from man page /nix/store/glh1jj2vy9h9h7nis6hf3lmrdknlyyl8-gtkwave-3.3.110/share/man/man1/vcd2fst.1.gz
complete -c vcd2fst -s v -l vcdname -d 'Specify VCD/FSDB/VPD/WLF input filename'
complete -c vcd2fst -s f -l fstname -d 'Specify FST output filename'
complete -c vcd2fst -s 4 -l fourpack -d 'Indicates that LZ4 should be used for value change data (default)'
complete -c vcd2fst -s F -l fastpack -d 'Indicates that fastlz should be used instead of LZ4 for value change data'
complete -c vcd2fst -l zlibpack -d 'Indicates that zlib should be used instead of LZ4 for value change data'
complete -c vcd2fst -s c -l compress -d 'Indicates that the entire file should be run through gzip on close'
complete -c vcd2fst -s p -l parallel -d 'Indicates that parallel mode should be enabled'
complete -c vcd2fst -s h -l help -d 'Show help screen'

