# vcd2lxt
# Autogenerated from man page /nix/store/glh1jj2vy9h9h7nis6hf3lmrdknlyyl8-gtkwave-3.3.110/share/man/man1/vcd2lxt.1.gz
complete -c vcd2lxt -o stats -d 'Prints out statistics on all nets in VCD file in addition to performing the c…'
complete -c vcd2lxt -o clockpack -d 'Apply two-way subtraction algorithm in order to identify nets whose value cha…'
complete -c vcd2lxt -o chgpack -d 'Emit data to file after being filtered through zlib (gzip)'
complete -c vcd2lxt -o linear -d 'Write out LXT in "linear" format with no backpointers'

