# vncpasswd
# Autogenerated from man page /nix/store/0b2bvviijkvq2nvm04dbq3lwlq7h742m-tigervnc-1.12.0/share/man/man1/vncpasswd.1.gz
complete -c vncpasswd -o rfbauth -d 'use via the -passwd option'
complete -c vncpasswd -s f -d 'Filter mode'

