# vvp
# Autogenerated from man page /nix/store/q0rhxcs2hfri6ja2fas671ywiszk20qr-iverilog-11.0/share/man/man1/vvp.1.gz
complete -c vvp -s i -d 'This flag causes all output to <stdout> to be unbuffered'
complete -c vvp -o llogfile -d 'This flag specifies a logfile where all MCI <stdlog> output goes'
complete -c vvp -o Mpath -d 'This flag adds a directory to the path list used to locate VPI modules'
complete -c vvp -o mmodule -d 'Tell the vvp run time to load the named module before executing the simulation'
complete -c vvp -s n -d 'This flag makes $stop or a <Control-C> a synonym for $finish'
complete -c vvp -s N -d 'This flag does the same thing as -n, but results in an exit code of 1 if the …'
complete -c vvp -s s -d Stop
complete -c vvp -s v -d 'Turn on verbose messages'
complete -c vvp -s V -d 'Print the version of the runtime, and exit'
complete -c vvp -o vcd -d 'This extended argument sets the wave dump format to VCD'
complete -c vvp -o lxt -o lxt-speed -o lxt-space -d 'These extended arguments set the wave dump format to lxt, possibly with forma…'
complete -c vvp -o lxt2 -o lxt2-speed -o lxt2-space
complete -c vvp -o lx2 -o lx2-speed -o lx2-space -d 'The LXT2 format is slower than LXT but usually takes less space, and is writt…'
complete -c vvp -o fst -o fst-speed -o fst-space
complete -c vvp -o fst-space-speed -o fst-speed-space -d 'This is a modern dumping format that is both faster and more compact than the…'
complete -c vvp -o none -d 'This flag can be used by itself or appended to the end of the above dumpers (…'
complete -c vvp -o sdf-warn -d 'When loading an SDF annotation file, this option causes the annotator to prin…'
complete -c vvp -o sdf-info -d 'When loading an SDF annotation file, this option causes the annotator to prin…'
complete -c vvp -o sdf-verbose -d 'This is shorthand for -sdf-info -sdf-warn'
complete -c vvp -o compatible -d 'This extended argument enables improved compatibility with other simulators'

