# vzt2vcd
# Autogenerated from man page /nix/store/glh1jj2vy9h9h7nis6hf3lmrdknlyyl8-gtkwave-3.3.110/share/man/man1/vzt2vcd.1.gz
complete -c vzt2vcd -s v -l vztname -d 'Specify VZT input filename'
complete -c vzt2vcd -s o -l output -d 'Specify optional VCD output filename'
complete -c vzt2vcd -s f -l flatearth -d 'Emit flattened hierarchies'
complete -c vzt2vcd -s c -l coalesce -d 'Coalesce bitblasted vectors'
complete -c vzt2vcd -s n -l notruncate -d 'Do not shorten bitvectors'

