# vztminer
# Autogenerated from man page /nix/store/glh1jj2vy9h9h7nis6hf3lmrdknlyyl8-gtkwave-3.3.110/share/man/man1/vztminer.1.gz
complete -c vztminer -s d -l dumpfile -d 'Specify VZT input dumpfile'
complete -c vztminer -s m -l match -d 'Specifies "bitwise" match data (binary, real, string)'
complete -c vztminer -s x -l hex -d 'Specifies hexadecimal match data that will automatically be converted to bina…'
complete -c vztminer -s n -l namesonly -d 'Indicates that only facnames should be printed in a gtkwave savefile compatib…'
complete -c vztminer -s c -l comprehensive -d 'Indicates that results are not to stop after the first match'

