# xml2stems
# Autogenerated from man page /nix/store/glh1jj2vy9h9h7nis6hf3lmrdknlyyl8-gtkwave-3.3.110/share/man/man1/xml2stems.1.gz
complete -c xml2stems -s V -l vl_sim -d 'Adds TOP hierarchy for Verilator sim.   Not necessary for other simulators'

