# zsoelim
# Autogenerated from man page /nix/store/jm090ms8ngq3c5g9v5jd0djplphnc8dr-man-db-2.9.4/share/man/man1/zsoelim.1.gz
complete -c zsoelim -s C -l compatible -d 'This flag is available for compatibility with other  soelim programs'
complete -c zsoelim -s h -l help -d 'Print a help message and exit'
complete -c zsoelim -s V -l version -d 'Display version information'

